create table exercise (id uuid not null, muscular_group_id uuid not null, name varchar(56) not null, description varchar(255), primary key (id));
create table exercise_set (id uuid not null, workout_id uuid, description varchar(255), name varchar(255), primary key (id));
create table exercise_setup (exercise_id uuid, exercise_set_id uuid, id uuid not null, observation varchar(255), repetitions varchar(255), rest varchar(255), series varchar(255), primary key (id));
create table muscular_group (id uuid not null, name varchar(255), primary key (id));
create table users (active_workout_id uuid, id uuid not null, email varchar(255), name varchar(255), password varchar(255), primary key (id));
create table workout (created_by_id uuid, id uuid not null, users_id uuid, description varchar(255), name varchar(255), primary key (id));
alter table if exists exercise add constraint FKdhly9nwp8agqc8e1k4e1h2vt6 foreign key (muscular_group_id) references muscular_group;
alter table if exists exercise_set add constraint FKhahvdyx4s9kxgjj163cb67qj7 foreign key (workout_id) references workout;
alter table if exists exercise_setup add constraint FKkmwm8mr90kshiyab3qvfhb1ug foreign key (exercise_id) references exercise;
alter table if exists exercise_setup add constraint FKcrwceierac7dib0aro74vcokb foreign key (exercise_set_id) references exercise_set;
alter table if exists users add constraint FKmccddlum1f6tmdre7vnx6ilaa foreign key (active_workout_id) references workout;
alter table if exists workout add constraint FKlfu214l35p571pvmwwu9okowh foreign key (created_by_id) references users;
alter table if exists workout add constraint FK1iatjg769unfobin55mqvq8fg foreign key (users_id) references users;
